---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

Below you will find information regarding my academic background and work experiences:

### Education
**Columbia University: Master of Public Health in Epidemiology (2020-2022)**

**University of California Davis: Bachelor's in Biotechnology (2015-2018)**

### Honors and Awards
Columbia: Huo Foundation Scholarship (2020-2022); UC Davis: David Britz Scholarship, University Honors Program (2015 – 2018)

### Technical Skills
* Python, R, SAS, SQL, Microsoft Access, VBA C, MATLAB, GraphPad Prism, Ingenuity Pathway Analysis

### Work Experience

#### Deloitte – Summer Associate (Healthcare) 
June 2021– August 2021

* Provided guidance and made strategic recommendations to help clients understand shifts and trends in the healthcare industry through conducting market research and assessing competitor landscape
* Engaged with client stakeholders to identify capability gaps that informed an operational plan to help clients achieve greater efficiencies through rapid redesign of business processes
* Developed an internal tool to reduce discrimination and promote inclusion for minority groups (AAPI and Hispanic/Latinx) 

#### Center for Statistical Genetics – Data Science Scholar 
January 2021– June 2021

* Used Python and bioinformatics knowledge to automate a process for identifying disease-causing variants for rare neurological disorders using RNA-sequencing data
* Increased efficiency in solving a patient case from 1 hour to ~10 minutes, providing patient families in developing countries with a definite diagnosis and path for treatment

#### Maze Therapeutics – Research Associate I                                                                     
April 2019 – May 2021

* Developed and optimized cell-based assays to validate metabolic drug targets and therapeutic approaches 
*	Evaluated competitive landscape for novel drug targets through literature searches, advising project leads on the demand for new treatments and feasibility of drug development 
*	Supervised and advised local and international contract research organizations (CROs) for assay development, ensuring all deliverables were presented on time and within budget, and communicating progress to internal leadership team
*	Wrote detailed protocols for research studies and trained 3 employees to successfully reproduce assays and data analyses

#### Translational Cognitive Neuroscience Lab – ASPIRE Program Intern
September 2016 – February 2019

*	Utilized machine learning to train support vector machines for classification of electroencephalography studies in MATLAB
*	Designed and conducted electroencephalography (EEG) and eye-tracking studies in heathy subjects to understand dysfunction of cognition in disorders such as schizophrenia, presenting research at the Center for Mind and Brain symposium
*	Managed distribution and collection of participant data in secure databases and maintained IRB protocols 

#### California National Primate Research Center – Undergraduate Researcher
May 2017 – December 2018

*	Used Python to analyze ozone and particulate matter exposures from California wildfires in monkeys, leveraging millions of data points collected by an air quality monitoring system over 9 years
*	Created a statistical model to correlate early life wildfire exposures to respiratory health impacts for honors thesis
*	Manuscript in Progress; Poster session at Undergraduate Research Conference + 9th annual Lung Day at UC Davis
*	Implemented and optimized laboratory protocols, managed inventory system, and trained new students

#### Amgen – Cardiometabolic Intern
June 2018 – September 2018

* Used data mining to identify novel gene targets controlling heart contractility and rhythm 
*	Optimized gene knockdowns in stem-cell derived cardiomyocytes using quantitative polymerase chain reactions (qPCRs)
*	Characterized electrical activity in the cardiomyocytes through voltage manipulation in electrophysiological assays 

### Volunteer Activities

* Volunteer at animal shelter – Fostering dogs that are surrendered, administering medicine for sick animals
* SEVA Health Clinic – Provided intake measurements and health education to uninsured community in Sacramento
* Project RISHI – Addressed developmental disparities in underprivileged communities by providing health education
to villagers in India and partnering with local businesses to sell cards hand-made by an HIV+ community of women  

### Leadership

* President of Healthcare Data Analytics Club (2020 - Present)
* History and Board Member of Synthethic Biology Club (2017-2018)





Click [here](index.html) to return to the home page



